<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://tempuri.org/" name="DateServiceWs">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://tempuri.org/" schemaLocation="DateServiceWs1.xsd"/>
    </xsd:schema>
  </types>
  <message name="getDate">
    <part name="parameters" element="tns:getDate"/>
  </message>
  <message name="getDateResponse">
    <part name="parameters" element="tns:getDateResponse"/>
  </message>
  <portType name="DateServiceWs">
    <operation name="getDate">
      <input message="tns:getDate" wsam:Action="http://tempuri.org/DateServiceWs/getDateRequest"/>
      <output message="tns:getDateResponse" wsam:Action="http://tempuri.org/DateServiceWs/getDateResponse"/>
    </operation>
  </portType>
  <binding name="DateServiceWsPortBinding" type="tns:DateServiceWs">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getDate">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="DateServiceWs">
    <port name="DateServiceWsPort" binding="tns:DateServiceWsPortBinding">
      <soap:address location="http://localhost:7101/ViewController/DateServiceService"/>
    </port>
  </service>
</definitions>